name: project_test2
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  intl: ^0.20.2

  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_messaging: ^16.1.1
  firebase_storage: ^13.0.0

  flutter_bloc: ^9.0.0
  equatable: ^2.0.5

  supabase_flutter: ^2.5.6

  provider: ^6.1.2
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  image: ^4.1.7
  share_plus: ^13.1.0
  flutter_local_notifications: ^22.0.0
  video_player: ^2.8.2
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.2.5
  webview_flutter: ^4.4.2
  file_picker: ^12.0.0-beta.5
  http: ^1.2.0
  shared_preferences: ^2.5.5
  font_awesome_flutter: ^11.0.0
  flutter_svg: ^2.2.4
  record: ^7.0.0
  just_audio: ^0.10.5
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  flutter_slidable: ^4.0.3
  local_auth: ^3.0.1
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  app_links: ^7.1.1
  gal: ^2.3.2
  flutter_secure_storage: ^10.3.0
  firebase_app_check: ^0.4.4+2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "lib/assets/icons/android/play_store_512.png"
  image_path: lib/assets/icons/android/play_store_512.png
  min_sdk_android: 21
<<<<<<< HEAD
  adaptive_icon_background: "#051b44"
  adaptive_icon_foreground: "lib/assets/icons/android/play_store_512.png"
=======
  adaptive_icon_background: "#FFFFFF"
>>>>>>> 5bfe229f9bee06786262c5ea1015fcaa7aed2f3c

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/certs/