org.gradle.jvmargs=-Xmx3072m -XX:+UseParallelGC -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -Dfile.encoding=UTF-8
org.gradle.workers.max=4
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
android.useAndroidX=true
kotlin.incremental=true
kotlin.compiler.execution.strategy=in-process
android.enableOnDemandModules=false
android.newDsl=true
android.builtInKotlin=true
org.gradle.caching=true
