// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiCrvL9XDVaItRkwG7iamV7jrY5sVzHDc',
    appId: '1:201349891361:web:351852060e565fcdd6ea60',
    messagingSenderId: '201349891361',
    projectId: 'university-connect-52779',
    authDomain: 'university-connect-52779.firebaseapp.com',
    storageBucket: 'university-connect-52779.firebasestorage.app',
    measurementId: 'G-0BXGB1NC54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC4mpmwc7kovzqpqnjdpqPt4xzy_9SZvw',
    appId: '1:201349891361:android:3dd2bfaad9de4fc9d6ea60',
    messagingSenderId: '201349891361',
    projectId: 'university-connect-52779',
    storageBucket: 'university-connect-52779.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4wYVJIJ8MmGdg9Fm0ZAK0yLpooSnZeo8',
    appId: '1:201349891361:ios:fb72bd7b70d93f58d6ea60',
    messagingSenderId: '201349891361',
    projectId: 'university-connect-52779',
    storageBucket: 'university-connect-52779.firebasestorage.app',
    iosBundleId: 'com.example.projectTest2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4wYVJIJ8MmGdg9Fm0ZAK0yLpooSnZeo8',
    appId: '1:201349891361:ios:fb72bd7b70d93f58d6ea60',
    messagingSenderId: '201349891361',
    projectId: 'university-connect-52779',
    storageBucket: 'university-connect-52779.firebasestorage.app',
    iosBundleId: 'com.example.projectTest2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiCrvL9XDVaItRkwG7iamV7jrY5sVzHDc',
    appId: '1:201349891361:web:e4a36cd39e998248d6ea60',
    messagingSenderId: '201349891361',
    projectId: 'university-connect-52779',
    authDomain: 'university-connect-52779.firebaseapp.com',
    storageBucket: 'university-connect-52779.firebasestorage.app',
    measurementId: 'G-WXK58WHPK0',
  );
}
